### ISSUE TITLE
CELFileData.h able to read command console genertic data file format?

### ISSUE THREAD

**Issue by gjmzajac** [HenrikBengtsson/Affx-Fusion-SDK#1]
My CEL files appear to be in the command console genertic data file format described here: https://www.affymetrix.com/support/developer/powertools/changelog/gcos-agcc/generic.html can I read them using CELFileData.h? Right now, CelFile.Exists() returns true but CelFile.Read() returns false.

**Comment by HenrikBengtsson** [comment]
Sorry, I'm only using the repos for archiving Affymetrix releases of their Fusion SDK.  No support what so ever. I'm not affiliated with Affymetrix.  From README file:

> This unofficial repository [...]
